artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/Ronak-Sah/Datafiles/raw/refs/heads/main/samsum.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir : artifacts/data_validation
  status_file : artifacts/data_validation/status_file.txt
  all_required_files : ["train.csv","test.csv","validation.csv"]
  

data_transformation:
  root_dir : artifacts/data_transformation
  data_path : artifacts/data_ingestion/samsum
  tokenizer_name : "google/pegasus-xsum"


model_trainer:
  root_dir : artifacts/model_trainer
  data_path : artifacts/data_transformation/samsum_dataset
  model_name : "google/pegasus-xsum"
   

model_evaluation:
  root_dir : artifacts/model_evaluation
  data_path : artifacts/data_transformation/samsum_dataset
  model_path : artifacts/model_trainer/pegasus-samsum-model
  tokenizer_path : artifacts/model_trainer/Tokenizer
  metric_file_name : artifacts/model_evaluation/metrics.csv